# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-30 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20180328_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Date from')),
                ('date_to', models.DateField(verbose_name='Date to')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Comment')),
                ('sent_to_jira', models.BooleanField(default=True, verbose_name='Send to JIRA')),
                ('slack_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to='users.SlackUser', verbose_name='Slack user')),
            ],
            options={
                'verbose_name': 'Vacation record',
                'verbose_name_plural': 'Vacation records',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vacationrecord',
            unique_together=set([('slack_user', 'date_from', 'date_to')]),
        ),
    ]
