# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-30 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrecord',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Is processed'),
        ),
    ]
